// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcJFQSTnYyAX6EU53J_b4L1ckLPELC_IQ',
    appId: '1:194426924267:web:29a6fb5e988a8d56d522ae',
    messagingSenderId: '194426924267',
    projectId: 'borrowmydriveway',
    authDomain: 'borrowmydriveway.firebaseapp.com',
    storageBucket: 'borrowmydriveway.firebasestorage.app',
    measurementId: 'G-J3QQ87Q4H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdpaatFG6jtZFdoFgAEjVV8KEd2JmZ7oo',
    appId: '1:194426924267:android:2363aef84b3107efd522ae',
    messagingSenderId: '194426924267',
    projectId: 'borrowmydriveway',
    storageBucket: 'borrowmydriveway.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt1tEckorMPYaQbowi_hofO1ibGQx2hlw',
    appId: '1:194426924267:ios:786a7ba8de736425d522ae',
    messagingSenderId: '194426924267',
    projectId: 'borrowmydriveway',
    storageBucket: 'borrowmydriveway.firebasestorage.app',
    iosBundleId: 'com.example.borrowMyDriveway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt1tEckorMPYaQbowi_hofO1ibGQx2hlw',
    appId: '1:194426924267:ios:786a7ba8de736425d522ae',
    messagingSenderId: '194426924267',
    projectId: 'borrowmydriveway',
    storageBucket: 'borrowmydriveway.firebasestorage.app',
    iosBundleId: 'com.example.borrowMyDriveway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcJFQSTnYyAX6EU53J_b4L1ckLPELC_IQ',
    appId: '1:194426924267:web:28f81434b980b807d522ae',
    messagingSenderId: '194426924267',
    projectId: 'borrowmydriveway',
    authDomain: 'borrowmydriveway.firebaseapp.com',
    storageBucket: 'borrowmydriveway.firebasestorage.app',
    measurementId: 'G-DN0PRJPHLN',
  );

}