// main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'firebase_options.dart'; // This file is generated by the FlutterFire CLI
import 'screens/auth/auth_gate.dart';

// The main entry point for the application.
void main() async {
  // Ensure that the Flutter binding is initialized before calling native code.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase. This must be done before using any Firebase services.
  // It uses the DefaultFirebaseOptions.currentPlatform which is generated by FlutterFire.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await FirebaseAppCheck.instance.activate(
    // You can also use a debug provider for local testing
    androidProvider: AndroidProvider.playIntegrity,
    appleProvider: AppleProvider.appAttest,
  );

  // Run the main application widget.
  runApp(const BorrowMyDrivewayApp());
}

// The root widget of your application.
class BorrowMyDrivewayApp extends StatelessWidget {
  const BorrowMyDrivewayApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Borrow My Driveway',
      debugShowCheckedModeBanner: false,
      // Theming for the app. You can customize colors, fonts, etc. here.
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        // Let's define some nice colors for our theme.
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF0052D4), // A nice, modern blue
          primary: const Color(0xFF0052D4),
          secondary: const Color(0xFF65C7F7),
          surface: Colors.grey[100],
        ),
        // Define the look of our buttons
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF0052D4), // Button background color
            foregroundColor: Colors.white, // Button text color
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 24),
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: Colors.grey),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: Color(0xFF0052D4), width: 2),
          ),
          filled: true,
          fillColor: Colors.white,
        ),
      ),
      // The home property defines the first screen to be displayed.
      // We'll replace this later with a widget that checks if the user is logged in.
      home: const AuthGate(),
    );
  }
}
